chenxiaolong/Custota

- app/build.gradle.kts
- app/src/main/res/values-vi/values.xml
- app/src/main/res/xml/locales_config.xml
I added translation for Vietnamese so my family members can read the app to update the OS by themself on local network. I already checked for typos and made sure that it's easy to understand and closest to Vietnamese language style on Android.
Thank you so much for the project, again!
Edit: Do you accept translation for the README.md too?
> Add Vietnamese translation for Cusota app

- app/src/main/java/com/chiller3/custota/Notifications.kt
- app/src/main/java/com/chiller3/custota/updater/UpdaterService.kt
On the initial installation of Custota, the first app launch will set up the periodic updater job and Android will fire up one run of UpdaterService almost immediately. UpdaterService is started with startForegroundService() and because the user hasn't had the chance to configure a URL yet, the service immediately calls stopService() and exits. This is not allowed by Android. Even if a service immediately exits, it must still call startForeground().
This commit adds the startForeground() call whenever UpdaterService runs, even if there's nothing to do. To avoid a pointless notification being shown, the FOREGROUND_SERVICE_IMMEDIATE is not used unless an actual update check is going to be run.
Fixes: #7
> Fix crash when UpdaterService is started for the first time

- app/module/post-fs-data.sh
First stage `init` no longer creates the directory unconditionally [1]. It only does so if there's actually an APEX-packaged SELinux policy.
[1] https://android.googlesource.com/platform/system/core/+/d01921034cc63c9f0942b5fb451cbc971e7407b1%5E%21/
Issue: #11
> post-fs-data.sh: Explicitly create /dev/selinux

- custota-tool/src/main.rs
This fixes passing non-UTF-8 paths for `--cert` on Linux.
> custota-tool: Fix missing value_parser for --cert

- README.md
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/chiller3/custota/updater/UpdaterService.kt
GrapheneOS 14 introduced [1], which unconditionally changes the system exempted foreground type to the special use foreground type within `ServiceInfo`. This applies to all packages, not just gmscompat-related packages.
However, they don't wrap the corresponding `startForeground()` calls, so the mismatch causes Custota's service to crash. We can work around this GrapheneOS bug by switching to the special use foreground type, which currently has no downsides compared to the system exempted foreground type.
Fixes: #22
[1]: https://github.com/GrapheneOS/platform_frameworks_base/commit/a350b31d35d2218d0c8ba69772d5b1b95f92c236
> Switch to special use foreground service type

- app/src/main/java/com/chiller3/custota/updater/UpdaterThread.kt
nginx only returns Accept-Ranges if the request was sent without the Ranges header.
Fixes: #29
> UpdaterThread: Check for Content-Range instead of Accept-Ranges

- README.md
- app/module/post-fs-data.sh
Android 14 QPR2 (2024 March security update) dropped support for loading APEX SELinux policies [1] and thus, /dev/selinux/apex_seapp_contexts.
This commit updates the post-fs-data hook script to modify /system/etc/selinux/plat_seapp_contexts instead, which is the only other file that's applicable to apps stored on the system partition. The hook script takes extra care to ensure that an outdated modified version of this file won't be loaded because that can result in boot loops.
[1] https://android.googlesource.com/platform/external/selinux/+/e9448817b37b2d14ab8e00dfff4b60347512aae7%5E%21/
Fixes: #40
> Switch to modifying /system/etc/selinux/plat_seapp_contexts

- app/src/main/java/com/chiller3/custota/Preferences.kt
- app/src/main/java/com/chiller3/custota/settings/SettingsFragment.kt
- app/src/main/java/com/chiller3/custota/settings/SettingsViewModel.kt
- app/src/main/java/com/chiller3/custota/updater/OtaPaths.kt
- app/src/main/java/com/chiller3/custota/updater/UpdaterThread.kt
- app/src/main/res/values-vi/values.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences_root.xml
This is useful when the csig is signed by a different key than the OTA and installing the certificate in `/system/etc/security/otacerts.zip` isn't desired.
Issue: #47
> Add debug feature for installing custom csig validation certs

- app/src/main/java/com/chiller3/custota/updater/UpdaterThread.kt
CalyxOS modifies `Build.VERSION.SECURITY_PATCH` so that it queries `ro.build.version.real_security_patch` instead of
`ro.build.version.security_patch`. However, despite the name, the `real_security_patch` value is fake. The security patch level in the OTA metadata's postconditions matches the normal `security_patch`.
Fixes: #51
> UpdaterThread: Work around lying Build.VERSION.SECURITY_PATCH

- app/module/boot_common.sh
- app/module/post-fs-data.sh
- app/proguard-rules.pro
- app/src/main/java/com/chiller3/custota/standalone/ClearPackageManagerCaches.kt
Some devices don't set the system time properly during boot, causing Android's package manager to fail to invalidate cached package info. Work around this by forcibly deleting the relevant cache files.
Issue: #51
See: chenxiaolong/BCR#323
> Clear package manager cache entries on boot

- app/module/post-fs-data.sh
The SELinux policy in newer Android builds no longer allows update_engine to read the target of a `system_security_cacerts_file` symlink.
> post-fs-data.sh: Copy CA certificates directory instead of symlinking

- .github/workflows/ci.yml
- README.md
The precompiled binaries are compiled for aarch64 API 31, which should work for every device that avbroot supports.
Issue: #60
> custota-tool: Add support for cross-compiling to Android

- app/src/main/java/com/chiller3/custota/standalone/ClearPackageManagerCaches.kt
This makes it possible for these tools to be run from an init script without losing the output. There is no impact to the Magisk scripts since the logcat output is captured there anyway.
> standalone: Log output to logcat

- app/module/post-fs-data.sh
Letting Magisk handle the mounting breaks when multiple modules need to read the file and append to it. Magisk's mounting does not occur until all modules' `post-fs-data.sh` scripts have completed.
> Bind mount plat_seapp_contexts ourselves

- app/src/main/java/com/chiller3/custota/updater/UpdaterJob.kt
- app/src/main/res/values/strings.xml
It appears on that for some folks running the Android 15 beta, Android's job scheduler implementation is broken and returns a null Network instance. This commit adds support for falling back to the currently active network if the Require Unmetered Network option is turned off. Otherwise, the only thing we can do is show a notification to tell the user to turn that option off.
Closes: #68
> UpdaterJob: Add support for falling back to active network

- Cargo.lock
- custota-selinux/Cargo.toml
- custota-selinux/src/main.rs
This causes the file modification timestamp to change, which some apps use to detect if the SELinux policy has been modified.
Closes: #72
> custota-selinux: Avoid truncating /sys/fs/selinux/load

- README.md
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/chiller3/custota/updater/UpdateEngineError.kt
- app/src/main/java/com/chiller3/custota/updater/UpdateEngineStatus.kt
- app/src/main/java/com/chiller3/custota/updater/UpdaterBootReceiver.kt
- app/src/main/java/com/chiller3/custota/updater/UpdaterService.kt
- app/src/main/java/com/chiller3/custota/updater/UpdaterThread.kt
- app/src/main/res/values/strings.xml
On virtual A/B devices, after an OTA is installed and the device is rebooted, the system will merge the new data from the copy-on-write volumes to the actual partitions. This process takes a few minutes and most users aren't aware that it is happening.
It also causes some weird behavior with Custota. If the user tried to check for updates during this process, the notification would say the updater is initializing for a few minutes and then report that the OTA was successfully installed (again). Let's fix this by showing what is actually going on.
This commit also fixes a couple other notification issues:
* The `UpdaterThread.ProgressType.INIT` state has been removed since it races with `onStatusUpdate()` and sometimes causes the initialization message to be shown longer than necessary …
> Show notification for post-reboot cleanup process after OTA update

- app/src/main/java/com/chiller3/custota/Notifications.kt
The only phases that report progress are the update and verification phases. The finalization and cleanup phases don't report their progress. Let's show an indeterminate progress bar to not mislead the user with a perpetually non-increasing progress bar.
> Show indeterminate progress bar when progress is at 0 percent

- app/src/main/java/com/chiller3/custota/updater/UpdaterBootReceiver.kt
- app/src/main/java/com/chiller3/custota/updater/UpdaterService.kt
- app/src/main/java/com/chiller3/custota/updater/UpdaterThread.kt
We only want to monitor update_engine's status immediate after boot so that we can show a notification during the snapuserd merge operation. We don't want to annoy the user with update check notifications.
> UpdaterThread: Add new MONITOR action

- .github/workflows/ci.yml
Due to what seems to be a bug in AGP, we can't lazily obtain the NDK directory, which breaks AGP's automatic NDK installation. We can work around that by manually installing it in the CI pipeline.
> ci.yml: Manually install the Android NDK

- .github/workflows/ci.yml
Otherwise, the x86_64-unknown-linux-gnu build running on Ubuntu 22.04 can use the cache from the aarch64-linux-android31 build that originally ran on Ubuntu 24.04. This fails due to some cached components having been compiled against a newer version of glibc.
This commit also stops using ubuntu-24.04 because qemu-user-static isn't needed. That was a leftover from copying things from avbroot.
> ci.yml: Use target name in Rust cache key

- custota-selinux/src/main.rs
Devices that launched with Android <11 use the kernel-based sdcardfs instead of the userspace FUSE daemon.
Fixes: #83
> custota-selinux: Add SELinux rules for sdcardfs

- app/module/post-fs-data.sh
- custota-tool/system-ca-certs/post-fs-data.sh
During early boot, Magisk first runs all `post-fs-data.sh` scripts and then it mounts each module's `<module dir>/system` overrides. This breaks support for using custom CA certs via the system-ca-certs module if it just so happens that filesystem ordering causes Custota to be loaded before system-ca-certs. Custota's gathering of the system certs would run before system-ca-certs, but Magisk's mounting of the resulting files would run after.
To make things easier to troubleshoot, both modules now use the module ID as the arbitrary string for the source device for the mount instead of just `tmpfs`.
This commit additionally fixes another issue with the upcoming version of Magisk. Magisk appears to "clean up" shadowed mount points now instead of just keeping them around and relying on Linux's …
> post-fs-data: Mount cacerts ourselves and unmount shadowed mount points

- app/module/post-fs-data.sh
- custota-tool/system-ca-certs/post-fs-data.sh
This fixes this module coexisting with other modules, like MSD, on the upcoming Magisk version.
See: https://github.com/chenxiaolong/MSD/pull/13
> post-fs-data: Add umount workaround for plat_seapp_contexts

- app/src/main/java/com/chiller3/custota/extension/CursorExtensions.kt
- app/src/main/java/com/chiller3/custota/extension/DocumentFileExtensions.kt
The original idea was fundamentally not workable. Nothing would cause the `use { ... }` block to end immediately after we stop consuming the iterator. I'm too used to languages with RAII.
> DocumentFileExtensions: Fix Cursor resource leak

- app/src/main/java/com/chiller3/custota/Notifications.kt
We don't use a different expanded notification message, so the default behavior is sufficient.
> Notifications: Avoid overriding expanded notification text

- Cargo.lock
- README.md
- app/src/main/java/com/chiller3/custota/updater/UpdaterThread.kt
- custota-tool/Cargo.toml
- custota-tool/src/main.rs
- deny.toml
When using Custota in conjunction with avbroot, there may be situations where a new patched OTA has the same version as the currently running OS. The most common example is updating Magisk.
With this commit, if the OTA's fingerprint matches the current OS fingerprint, Custota will compare the vbmeta digest to determine if an update is necessary. This should reliably detect every scenario where the OTA's version is the same, but the partition contents differ.
The vbmeta digest is not readily accessible in an OTA, so custota-tool will compute it when generating the csig file. This is an unfortunately an expensive operation that requires extracting partitions from the OTA, so it will slow down custota-tool a decent bit.
Because Custota's csig file parser is strict, the file format version …
> Use vbmeta digest to detect same-version upgrades

- Cargo.lock
- custota-tool/Cargo.toml
- custota-tool/src/main.rs
This way, users don't need to downgrade to an older version just to generate the files.
Issue: #94
> custota-tool: Add support for generating version 1 csig files

- app/src/main/java/com/chiller3/custota/updater/UpdaterThread.kt
The versioning of the two file formats unfortunately didn't work out as well as I hoped. To support older versions of Custota, the server would need to keep serving the old file formats without any good upgrade path besides doing a hard cutover at some point.
Instead, let's try taking a page from the protobuf book and just make version 2 extensible by adding new fields. Custota from now on will just ignore fields it does not understand. I'll plan on having custota-tool output all fields forever for future backwards compatibility.
Issue: #94
> Allow unknown keys when parsing csig files and update JSON files

- app/build.gradle.kts
- app/module/post-fs-data.sh
This is more reliable and has better compatibility than trying to mount things ourselves. Any module that modifies plat_seapp_contents and includes the same command will produce the same output file, so the order that Magisk/KernelSU loads and mounts modules does not matter. Currently, MSD and Custota are the only two modules known to modify this file.
MSD version of this PR: https://github.com/chenxiaolong/MSD/pull/26
> post-fs-data.sh: Combine seapp snippets from all modules to produce full file

- README.md
- app/src/main/java/com/chiller3/custota/settings/SettingsFragment.kt
- app/src/main/java/com/chiller3/custota/updater/UpdaterJob.kt
- app/src/main/java/com/chiller3/custota/updater/UpdaterThread.kt
The `REVERT` and `MONITOR` jobs now no longer require a network connection and the unmetered network restriction no longer applies to `CHECK` jobs. The battery restriction now only applies to the `INSTALL` job.
Fixes: #104
> Only add network/battery restrictions to scheduled jobs when needed

- app/src/main/java/com/chiller3/custota/updater/UpdaterJob.kt
- app/src/main/java/com/chiller3/custota/updater/UpdaterService.kt
- app/src/main/res/values/strings.xml
We'll now try to query the capabilities of the active network in the fallback path so that the job will still run if the network satisfies the unmetered network requirement.
Since the fallback path (querying the active network) is no longer limited compared to the normal path (JobScheduler providing a valid network), the notification telling users about the Android 15 bug has been removed.
> Improve workaround for Android 15 null network bug

- README.md
- custota-tool/src/main.rs
This will display the contents of a csig file and optionally verify its signature. This way, openssl doesn't need to be manually installed on systems where it doesn't come preinstalled.
> Add custota-tool show-csig subcommand

- app/src/main/java/com/chiller3/custota/settings/SettingsFragment.kt
- app/src/main/java/com/chiller3/custota/updater/UpdaterJob.kt
This avoids needing to wake up the device for a no-op.
> UpdaterJob: Cancel periodic job when automatic checks are disabled

- app/module/post-fs-data.sh
- app/src/main/java/com/chiller3/custota/standalone/ClearBadJobSchedulerData.kt
For unknown reasons, there have been two instances in the wild where Android, at some point, reassigned Custota's app UID. Perhaps something caused Custota's APK to disappear temporarily for one boot?
When this happens, the JobScheduler XML file for the old UID gets left behind. While the old job does not show up in `dumpsys jobscheduler`, it still continues to run. This can cause crashes when UpdaterJob is launched with invalid old parameters.
This commit works around the problem by deleting JobScheduler XML files with a matching package name, but invalid UID, during boot.
Fixes: #116
> Clear invalid JobScheduler data on boot

- app/src/main/java/com/chiller3/custota/extension/UriExtensions.kt
- app/src/main/java/com/chiller3/custota/settings/SettingsFragment.kt
- app/src/main/java/com/chiller3/custota/updater/UpdaterJob.kt
- app/src/main/java/com/chiller3/custota/updater/UpdaterThread.kt
There's no reason Custota can't work fully offline when the OTA files exist in a local directory. Currently, this only works for Android's builtin local SAF providers: the external storage, media, and downloads providers. This covers every use case aside from selecting files from a third party local document provider. Unfortunately, there is no way to find out which SAF root a document belongs to or whether it has `FLAG_LOCAL_ONLY` set.
> Don't require network access when OTA source is local

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/chiller3/custota/MainApplication.kt
- app/src/main/java/com/chiller3/custota/updater/UpdaterLauncherActivity.kt
This does the same thing as the normal manual check for updates option, except with fewer steps. There is a small UX issue where the home screen's shortcuts popup does not close because we launch a UI-less Activity to schedule the UpdaterJob. This is still better than having the UI flicker due to a non-UI-less Activity.
> Add launcher shortcut to check for updates

- app/src/main/java/com/chiller3/custota/updater/UpdaterService.kt
- app/src/main/java/com/chiller3/custota/updater/UpdaterThread.kt
- custota-tool/src/main.rs
Some Nothing devices ship firmware for multiple regions in the same full OTA. These have the default fingerprint in `/system/build.prop` and then conditionally load region-specific propery files from `/odm/etc`. The OTA metadata lists all of these fingerprints in the postconditions.
Fixes: #129
> Allow OTAs with multiple fingerprints in postconditions

- README.md
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/chiller3/custota/MainApplication.kt
- app/src/main/java/com/chiller3/custota/Notifications.kt
- app/src/main/java/com/chiller3/custota/Preferences.kt
- app/src/main/java/com/chiller3/custota/extension/UriExtensions.kt
- app/src/main/java/com/chiller3/custota/settings/SettingsFragment.kt
- app/src/main/java/com/chiller3/custota/updater/UpdaterBootReceiver.kt
- app/src/main/java/com/chiller3/custota/updater/UpdaterService.kt
- app/src/main/java/com/chiller3/custota/updater/UpdaterThread.kt
Automatic checks and automatic installs can now run before the user has unlocked the device following a reboot.
To avoid leaking information (eg. in case the device was stolen), only update check and success notifications are shown on the lock screen. The installation progress and failure messages are hidden until the device is unlocked. This also means an ongoing update cannot be paused or cancelled while the device is locked without physically interrupting the internet connection.
If the user uses a local directory or any other SAF provider as the source, then direct boot support is disabled. Local directories are not accessible and we can't know whether a SAF provider also supports direct boot.
The user's preferences will automatically be migrated from credential-protected storage to …
> Add support for direct boot

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/chiller3/custota/MainApplication.kt
- app/src/main/java/com/chiller3/custota/PostUnlockInit.kt
- app/src/main/java/com/chiller3/custota/PostUnlockInitReceiver.kt
- app/src/main/java/com/chiller3/custota/Preferences.kt
- app/src/main/java/com/chiller3/custota/settings/SettingsFragment.kt
The migration logic introduced in 5.12 was incorrect and allowed the migration to run while BFU. This marked the migration as completed, even though nothing was migrated, causing all settings to be reset.
This commit fixes the broken migration and also ensures that it will actually run when the user unlocks their device. If the user hasn't already reconfigured the app after the 5.12 upgrade, then the migration will be reattempted, even though it is marked as complete.
> Fix preferences migration improperly detecting BFU

- app/src/main/java/com/chiller3/custota/Notifications.kt
- app/src/main/java/com/chiller3/custota/updater/UpdaterService.kt
- app/src/main/java/com/chiller3/custota/updater/UpdaterThread.kt
For some reason, update_engine only provides intermediate progress updates for the snapuserd merge operation if another callback is registered using `IUpdateEngine.cleanupSuccessfulUpdate()`. The primary callback only receives completion statuses. Weirdly, there's also no binder call to unregister this callback. It can't be removed until the merge operation completes or the binder client process dies. That is fine for Custota's use case since `UpdaterThread` does not exit until the operation is complete anyway.
This commit also updates the notification logic so that progress notifications that do not contain action buttons, like the one for merge operations, are allowed to be shown on the lock screen. This way, the user can see the progress while in BFU.
> Show determinate progress bar for snapuserd merge

- app/src/main/java/com/chiller3/custota/updater/UpdaterThread.kt
In some scenarios, the merge callback can be cleared sooner than when it was initially set, tripping up the assertion we do in `unbind()`.
> Fix possible crash with merge callback

- app/proguard-rules.pro
r8 is deduplicating the exception classes. While they have identical source code class definitions, they are semantically different.
> Work around r8 miscompilation in UpdaterThread exceptions
